import{a as P,S as v,i as $}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();async function h(o,t){const c="https://pixabay.com",i="/api/",e="?key=43293372-b4e22d1edd78f6a49221e5436",r=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`,s=c+i+e+r;return(await P.get(s)).data}const u=document.querySelector(".gallery");function p(o){const t=o.hits.map(({webformatURL:i,largeImageURL:e,tags:r,likes:s,views:f,comments:E,downloads:S})=>`<li class= "gallery-item">
        <a class="gallery-link" href="${e}">
        <img class="gallery-img" src="${i}" alt="${r}"</a> 
        <div class="image-description">
        <p class = "comment">Likes: ${s}</p>
        <p class = "comment">Views: ${f}</p>
        <p class = "comment">Comments: ${E}</p>
        <p class = "comment">Downloads: ${S}</p></div>
        </li>`).join("");u.insertAdjacentHTML("beforeend",t),new v(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const q=document.querySelector(".img-form"),g=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");q.addEventListener("submit",M);m.addEventListener("click",O);let l,a,y;async function M(o){if(o.preventDefault(),L(),u.innerHTML="",l=o.target.elements.picture.value.trim(),a=1,l===""){n("Sorry, there are no search terms entered. Please try again!");return}b();try{const t=await h(l,a);if(y=Math.ceil(t.totalHits/15),t.totalHits===0){d(),n("Sorry, there are no images matching your search query. Please try again!");return}p(t)}catch(t){n(t)}d(),w(),o.target.reset()}async function O(){a+=1,b();try{const t=await h(l,a);p(t)}catch(t){n(t)}d(),w();const o=u.firstElementChild.getBoundingClientRect().height;window.scrollBy({behavior:"smooth",top:o*2})}function x(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function w(){a>=y?(L(),n("We're sorry, but you've reached the end of search results.")):x()}function n(o){$.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
